INSERT INTO menu (pk_menu, nome_alimento, cat_alimento, desc_alimento, preco) VALUES (1, 'Paste de queijo', 'Entrada', 'Porção com 6 pastéis de queijo.', 25.00);
INSERT INTO menu (pk_menu, nome_alimento, cat_alimento, desc_alimento, preco) VALUES (2, 'Iscas de frango', 'Entrada', 'Iscas de filé de peito de frango empanados e fritos, acompanha molho da casa.', 35.00);
INSERT INTO menu (pk_menu, nome_alimento, cat_alimento, desc_alimento, preco) VALUES (3, 'Tábua de frios', 'Entrada', '3 variedades de queijo, 3 variedades de embutidos e torradas.', 45.00);
INSERT INTO menu (pk_menu, nome_alimento, cat_alimento, desc_alimento, preco) VALUES (4, 'Gurjão de peixe', 'Entrada', 'Iscas de tilápia empanadas e fritas, acompanha molho tártaro.', 50.00);
INSERT INTO menu (pk_menu, nome_alimento, cat_alimento, desc_alimento, preco) VALUES (5, 'Filé com fritas', 'Prato principal', 'Filé mignon acompanhado de arroz, feijão, farofa e batatas fritas.', 45.90);
INSERT INTO menu (pk_menu, nome_alimento, cat_alimento, desc_alimento, preco) VALUES (6, 'Frango grelhado', 'Prato principal', 'Peito de frando grelhado com 3 acompanhamentos a escolher.', 39.90);
INSERT INTO menu (pk_menu, nome_alimento, cat_alimento, desc_alimento, preco) VALUES (7, 'Moqueca baiana', 'Prato principal', 'Moqueca baiana tradicional, com peixe em postas, pimentões, tomate e leite de côco. Acompanha arroz e farofa.', 54.90);
INSERT INTO menu (pk_menu, nome_alimento, cat_alimento, desc_alimento, preco) VALUES (8, 'Salada verde', 'Acompanhamento', 'Salada de alface, rúcula e agrião.', 19.90);
INSERT INTO menu (pk_menu, nome_alimento, cat_alimento, desc_alimento, preco) VALUES (9, 'Batatas fritas', 'Acompanhamento', 'Porção de batatas fritas individual.', 19.90);
INSERT INTO menu (pk_menu, nome_alimento, cat_alimento, desc_alimento, preco) VALUES (10, 'Arroz', 'Acompanhamento', 'Porção de arroz individual.', 15.00);
INSERT INTO menu (pk_menu, nome_alimento, cat_alimento, desc_alimento, preco) VALUES (11, 'Feijão', 'Acompanhamento', 'Porção de feijão individual.', 15.00);
INSERT INTO menu (pk_menu, nome_alimento, cat_alimento, desc_alimento, preco) VALUES (12, 'Farofa', 'Acompanhamento', 'Porção de farofa individual.', 15.00);
INSERT INTO menu (pk_menu, nome_alimento, cat_alimento, desc_alimento, preco) VALUES (13, 'Sorvete de morango', 'Sobremesa', 'Sorvete de morango Italiano.', 12.90);
INSERT INTO menu (pk_menu, nome_alimento, cat_alimento, desc_alimento, preco) VALUES (14, 'Sorvete de creme', 'Sobremesa', 'Sorvete de creme Italiano.', 12.90);
INSERT INTO menu (pk_menu, nome_alimento, cat_alimento, desc_alimento, preco) VALUES (15, 'Petit gateau', 'Sobremesa', 'Petit gateau acompanhado de sorvete de creme.', 22.50);
INSERT INTO menu (pk_menu, nome_alimento, cat_alimento, desc_alimento, preco) VALUES (16, 'Coca-cola', 'Bebida', 'Coca-cola lata 350ml com gelo e limão.', 7.50);
INSERT INTO menu (pk_menu, nome_alimento, cat_alimento, desc_alimento, preco) VALUES (17, 'Guaraná', 'Bebida', 'Guaraná lata 350ml com gelo e limão.', 7.50);
INSERT INTO menu (pk_menu, nome_alimento, cat_alimento, desc_alimento, preco) VALUES (18, 'Chopp', 'Bebida', 'Chopp Brahma servido na tulipa de 300ml.', 9.90);